import { getSession, signIn, signOut, useSession } from 'next-auth/client';
import Head from 'next/head'
import MainComponent from '../components/MainComponent';
import NHeader from '../components/Nheader';
import NHeader2 from '../components/Nheader2';

const Login = () => {

  
  const [ session, loading ] = useSession();

  if(session) {
    return (
      <div>
        <Head>
          <title>GOSUNGGUN Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/gosung_favicon.png" />
        </Head>
        <NHeader />
        <NHeader2 />
      </div>
    )
  }

  return (
    <MainComponent />
  )
}


export default Login;